### ISSUE TITLE
Fix weird spacing in sticky header

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/tghandbook#6]
The sticky headers are weirdly too close to the top edge, see pic:
![Sticky header issue](https://i.imgur.com/CMrpbeI.png)

I think I know what's at fault here (sticky headers "stack" on top of the main page title, but are not equal in height)

**Comment by Chr728** [comment]
@Hamcha  can I take care of this issue ?

**Comment by Hamcha** [comment]
Sure go ahead!

**Comment by Chr728** [comment]
@Hamcha  first time contributing , should I fork or no need to just I  can create my own branch and work ? also how do you just want it to be a bit far ? as long as its not too sticky its good ?

**Comment by Chr728** [comment]
@Hamcha  is there  a way to connect with you over discord ? just for a better communication

**Comment by Hamcha** [comment]
Sure, Hamcha#1337, you can find me on /tg/station Discord

**Comment by Hamcha** [comment]
Fixed by #9
